// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Typescript = require("typescript");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var program = Typescript.createProgram(/* array */["./sample.ts"], { });

var checker = program.getTypeChecker();

var sourceFiles = program.getSourceFiles();

sourceFiles.forEach((function (sourceFile) {
        if (sourceFile.isDeclarationFile) {
          return 0;
        } else {
          Typescript.forEachChild(sourceFile, (function (node) {
                  var match = node.name;
                  if (match !== undefined) {
                    var match$1 = checker.getSymbolAtLocation(match);
                    if (match$1 !== undefined) {
                      var symbol = match$1;
                      var type_ = checker.getTypeOfSymbolAtLocation(symbol, Belt_Option.getExn(symbol.valueDeclaration));
                      console.log(checker.typeToString(type_));
                      return /* () */0;
                    } else {
                      return /* () */0;
                    }
                  } else {
                    return /* () */0;
                  }
                }));
          return /* () */0;
        }
      }));

exports.program = program;
exports.checker = checker;
exports.sourceFiles = sourceFiles;
/* program Not a pure module */
