// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Typescript = require("typescript");

var program = Typescript.createProgram(/* array */["./sample.tsx"], Js_dict.fromList(/* :: */[
          /* tuple */[
            "jsx",
            "react"
          ],
          /* [] */0
        ]));

var checker = program.getTypeChecker();

var sourceFiles = program.getSourceFiles();

sourceFiles.forEach((function (sourceFile) {
        if (sourceFile.isDeclarationFile) {
          return 0;
        } else {
          Typescript.forEachChild(sourceFile, (function (node) {
                  var match = node.name;
                  if (match !== undefined) {
                    var match$1 = checker.getSymbolAtLocation(match);
                    if (match$1 !== undefined) {
                      var symbol = match$1;
                      var match$2 = symbol.valueDeclaration;
                      if (match$2 !== undefined) {
                        var type_ = checker.getTypeOfSymbolAtLocation(symbol, match$2);
                        console.log(checker.typeToString(type_));
                        return /* () */0;
                      } else {
                        return /* () */0;
                      }
                    } else {
                      return /* () */0;
                    }
                  } else {
                    return /* () */0;
                  }
                }));
          return /* () */0;
        }
      }));

exports.program = program;
exports.checker = checker;
exports.sourceFiles = sourceFiles;
/* program Not a pure module */
