// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Program = { };

var SourceFile = { };

var TypeChecker = { };

var $$Symbol = { };

var Type = { };

exports.Program = Program;
exports.SourceFile = SourceFile;
exports.TypeChecker = TypeChecker;
exports.$$Symbol = $$Symbol;
exports.Type = Type;
/* No side effect */
