// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

function syntaxKindToJs(param) {
  return param + 0 | 0;
}

function syntaxKindFromJs(param) {
  if (param <= 324 && 0 <= param) {
    return param - 0 | 0;
  }
  
}

var jsMapperConstantArray = /* array */[
  0,
  1,
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  256,
  512,
  1024,
  2048,
  4096,
  8192,
  16384,
  32768,
  65536,
  131072,
  262144,
  524288,
  4194304,
  33554432,
  3,
  768,
  2816,
  25358336,
  40960
];

function nodeFlagsToJs(param) {
  return Js_mapperRt.toInt(param, jsMapperConstantArray);
}

function nodeFlagsFromJs(param) {
  return Js_mapperRt.fromInt(28, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  0,
  1,
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  256,
  512,
  2048,
  536870912,
  28,
  92,
  24,
  2270,
  513,
  3071
];

function modifierFlagsToJs(param) {
  return Js_mapperRt.toInt(param, jsMapperConstantArray$1);
}

function modifierFlagsFromJs(param) {
  return Js_mapperRt.fromInt(19, jsMapperConstantArray$1, param);
}

function jsxFlagsToJs(param) {
  return param + 0 | 0;
}

function jsxFlagsFromJs(param) {
  if (param <= 3 && 0 <= param) {
    return param - 0 | 0;
  }
  
}

var TextRange = { };

exports.syntaxKindToJs = syntaxKindToJs;
exports.syntaxKindFromJs = syntaxKindFromJs;
exports.nodeFlagsToJs = nodeFlagsToJs;
exports.nodeFlagsFromJs = nodeFlagsFromJs;
exports.modifierFlagsToJs = modifierFlagsToJs;
exports.modifierFlagsFromJs = modifierFlagsFromJs;
exports.jsxFlagsToJs = jsxFlagsToJs;
exports.jsxFlagsFromJs = jsxFlagsFromJs;
exports.TextRange = TextRange;
/* No side effect */
